// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllocationCost(arg1:number,arg2:number):Promise<number>;

export function BudgetProjectedCost(arg1:number):Promise<number>;

export function BudgetTotalCost(arg1:number):Promise<number>;
