// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllocationCost(arg1, arg2) {
  return window['go']['controllers']['AnalysisController']['AllocationCost'](arg1, arg2);
}

export function BudgetProjectedCost(arg1) {
  return window['go']['controllers']['AnalysisController']['BudgetProjectedCost'](arg1);
}

export function BudgetTotalCost(arg1) {
  return window['go']['controllers']['AnalysisController']['BudgetTotalCost'](arg1);
}
