// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBudget(arg1, arg2, arg3) {
  return window['go']['controllers']['BudgetController']['CreateBudget'](arg1, arg2, arg3);
}

export function DeleteBudget(arg1) {
  return window['go']['controllers']['BudgetController']['DeleteBudget'](arg1);
}

export function GetBudget(arg1) {
  return window['go']['controllers']['BudgetController']['GetBudget'](arg1);
}

export function ListBudgets() {
  return window['go']['controllers']['BudgetController']['ListBudgets']();
}

export function UpdateBudget(arg1) {
  return window['go']['controllers']['BudgetController']['UpdateBudget'](arg1);
}
