// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllocation(arg1, arg2, arg3) {
  return window['go']['controllers']['BudgetController']['AddAllocation'](arg1, arg2, arg3);
}

export function CreateBudget(arg1, arg2, arg3, arg4) {
  return window['go']['controllers']['BudgetController']['CreateBudget'](arg1, arg2, arg3, arg4);
}

export function DeleteAllocation(arg1) {
  return window['go']['controllers']['BudgetController']['DeleteAllocation'](arg1);
}

export function DeleteBudget(arg1) {
  return window['go']['controllers']['BudgetController']['DeleteBudget'](arg1);
}

export function DuplicateBudget(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controllers']['BudgetController']['DuplicateBudget'](arg1, arg2, arg3, arg4, arg5);
}

export function GetBudget(arg1) {
  return window['go']['controllers']['BudgetController']['GetBudget'](arg1);
}

export function ListAllocations(arg1) {
  return window['go']['controllers']['BudgetController']['ListAllocations'](arg1);
}

export function ListBudgets(arg1) {
  return window['go']['controllers']['BudgetController']['ListBudgets'](arg1);
}

export function UpdateAllocationCost(arg1, arg2, arg3) {
  return window['go']['controllers']['BudgetController']['UpdateAllocationCost'](arg1, arg2, arg3);
}

export function UpdateBudget(arg1) {
  return window['go']['controllers']['BudgetController']['UpdateBudget'](arg1);
}
