// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateBudget(arg1:string,arg2:string,arg3:string):Promise<models.Budget>;

export function DeleteBudget(arg1:number):Promise<void>;

export function GetBudget(arg1:number):Promise<models.Budget>;

export function ListBudgets():Promise<Array<models.Budget>>;

export function UpdateBudget(arg1:models.Budget):Promise<void>;
