// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAllocation(arg1:number,arg2:number,arg3:number):Promise<void>;

export function CreateBudget(arg1:number,arg2:string,arg3:string,arg4:string):Promise<models.Budget>;

export function DeleteAllocation(arg1:number):Promise<void>;

export function DeleteBudget(arg1:number):Promise<void>;

export function DuplicateBudget(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<number>;

export function GetBudget(arg1:number):Promise<models.Budget>;

export function ListAllocations(arg1:number):Promise<Array<models.BudgetAllocation>>;

export function ListBudgets(arg1:number):Promise<Array<models.Budget>>;

export function UpdateAllocationCost(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateBudget(arg1:models.Budget):Promise<void>;
