// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['controllers']['CategoryController']['CreateCategory'](arg1, arg2, arg3, arg4);
}

export function DeleteCategory(arg1) {
  return window['go']['controllers']['CategoryController']['DeleteCategory'](arg1);
}

export function GetCategoryByID(arg1) {
  return window['go']['controllers']['CategoryController']['GetCategoryByID'](arg1);
}

export function ListCategories(arg1) {
  return window['go']['controllers']['CategoryController']['ListCategories'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['controllers']['CategoryController']['UpdateCategory'](arg1);
}
