// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['controllers']['CategoryController']['CreateCategory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteCategory(arg1) {
  return window['go']['controllers']['CategoryController']['DeleteCategory'](arg1);
}

export function GetCategory(arg1) {
  return window['go']['controllers']['CategoryController']['GetCategory'](arg1);
}

export function ListCategories() {
  return window['go']['controllers']['CategoryController']['ListCategories']();
}

export function UpdateCategory(arg1) {
  return window['go']['controllers']['CategoryController']['UpdateCategory'](arg1);
}
