// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCategory(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<models.Category>;

export function DeleteCategory(arg1:number):Promise<void>;

export function GetCategoryByID(arg1:number):Promise<models.Category>;

export function ListCategories(arg1:number):Promise<Array<models.Category>>;

export function UpdateCategory(arg1:models.Category):Promise<void>;
