// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateGroup(arg1:number,arg2:string,arg3:string):Promise<models.Group>;

export function DeleteGroup(arg1:number):Promise<void>;

export function GetGroup(arg1:number):Promise<models.Group>;

export function ListGroups():Promise<Array<models.Group>>;

export function UpdateGroup(arg1:models.Group):Promise<void>;
