// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroup(arg1, arg2, arg3) {
  return window['go']['controllers']['GroupController']['CreateGroup'](arg1, arg2, arg3);
}

export function DeleteGroup(arg1) {
  return window['go']['controllers']['GroupController']['DeleteGroup'](arg1);
}

export function GetGroup(arg1) {
  return window['go']['controllers']['GroupController']['GetGroup'](arg1);
}

export function ListGroups(arg1) {
  return window['go']['controllers']['GroupController']['ListGroups'](arg1);
}

export function UpdateGroup(arg1) {
  return window['go']['controllers']['GroupController']['UpdateGroup'](arg1);
}
