// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['controllers']['ProjectController']['CreateProject'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['controllers']['ProjectController']['DeleteProject'](arg1);
}

export function GetProject(arg1) {
  return window['go']['controllers']['ProjectController']['GetProject'](arg1);
}

export function ListProjects() {
  return window['go']['controllers']['ProjectController']['ListProjects']();
}

export function UpdateProject(arg1) {
  return window['go']['controllers']['ProjectController']['UpdateProject'](arg1);
}
