// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<models.Project>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetProject(arg1:number):Promise<models.Project>;

export function ListProjects():Promise<Array<models.Project>>;

export function UpdateProject(arg1:models.Project):Promise<void>;
