// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTag(arg1:number,arg2:string):Promise<models.Tag>;

export function CreateTransactionTag(arg1:number,arg2:number):Promise<models.TransactionTag>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteTransactionTag(arg1:number,arg2:number):Promise<void>;

export function GetTag(arg1:number):Promise<models.Tag>;

export function GetTags(arg1:number):Promise<Array<models.Tag>>;

export function GetTransactionTag(arg1:number,arg2:number):Promise<models.TransactionTag>;

export function ListTags(arg1:number):Promise<Array<models.Tag>>;

export function UpdateTag(arg1:models.Tag):Promise<void>;
