// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTag(arg1, arg2) {
  return window['go']['controllers']['TagController']['CreateTag'](arg1, arg2);
}

export function CreateTransactionTag(arg1, arg2) {
  return window['go']['controllers']['TagController']['CreateTransactionTag'](arg1, arg2);
}

export function DeleteTag(arg1) {
  return window['go']['controllers']['TagController']['DeleteTag'](arg1);
}

export function DeleteTransactionTag(arg1, arg2) {
  return window['go']['controllers']['TagController']['DeleteTransactionTag'](arg1, arg2);
}

export function GetTag(arg1) {
  return window['go']['controllers']['TagController']['GetTag'](arg1);
}

export function GetTags(arg1) {
  return window['go']['controllers']['TagController']['GetTags'](arg1);
}

export function GetTransactionTag(arg1, arg2) {
  return window['go']['controllers']['TagController']['GetTransactionTag'](arg1, arg2);
}

export function ListTags(arg1) {
  return window['go']['controllers']['TagController']['ListTags'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['controllers']['TagController']['UpdateTag'](arg1);
}
