// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTransaction(arg1:number,arg2:any,arg3:string,arg4:number,arg5:string,arg6:boolean,arg7:string):Promise<models.Transaction>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetTransaction(arg1:number):Promise<models.Transaction>;

export function ListTransactions(arg1:number,arg2:any,arg3:any):Promise<Array<models.Transaction>>;

export function UpdateTransaction(arg1:models.Transaction):Promise<void>;
