// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTransaction(arg1:string,arg2:number,arg3:string,arg4:string):Promise<models.Transaction>;

export function GetTransactions():Promise<Array<models.Transaction>>;
