// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTransaction(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:any,arg7:any):Promise<models.Transaction>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetTransaction(arg1:number):Promise<models.Transaction>;

export function ListTransactions(arg1:any):Promise<Array<models.Transaction>>;

export function UpdateTransaction(arg1:models.Transaction):Promise<void>;
