// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['controllers']['TransactionVM']['AddTransaction'](arg1, arg2, arg3, arg4);
}

export function GetTransactions() {
  return window['go']['controllers']['TransactionVM']['GetTransactions']();
}
