// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransaction(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['controllers']['TransactionController']['AddTransaction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteTransaction(arg1) {
  return window['go']['controllers']['TransactionController']['DeleteTransaction'](arg1);
}

export function GetTransaction(arg1) {
  return window['go']['controllers']['TransactionController']['GetTransaction'](arg1);
}

export function ListTransactions(arg1) {
  return window['go']['controllers']['TransactionController']['ListTransactions'](arg1);
}

export function UpdateTransaction(arg1) {
  return window['go']['controllers']['TransactionController']['UpdateTransaction'](arg1);
}
